### ISSUE TITLE
Broken link in wiki "how it works" section

### ISSUE THREAD

**Issue by jthiesen** [keeptalkinggame/ktanemodkit#1]
@keeptalkinggame 

The link to the framework github project is broken in the "how it works" section.

The current link is https://github.com/keeptalkinggame/keeptalkingframework, which is a 404.

The correct link would be https://github.com/keeptalkinggame/ktanemodframework

I can't fork the Wiki it seems, so I'll submit the issue as an issue like this instead. Hope you find it helpful.

**Comment by bkane** [comment]
Thanks for letting us know! Fixed!
