### ISSUE TITLE
Unable to build asset bundles using Unity 5.6

### ISSUE THREAD

**Issue by nilsmunch** [keeptalkinggame/ktanemodkit#20]
Both build methods seem to fail when trying to build with Unity 5.6 (even projects that previously worked just fine)

The complaint is as follows :

`Failed to build AssetBundle: No constructor found for UnityEditor.Scripting.MonoIsland::.ctor(UnityEditor.BuildTarget, System.String, System.String[], System.String[], System.String[], System.String)`

Any suggestions will be highly appreciated.

**Comment by ashbash1987** [comment]
KTaNE builds using Unity 5.4. The current modkit won't work properly for other versions of Unity, so I'd recommend installing a version of Unity 5.4.

**Comment by bkane** [comment]
(Closing this as it probably no longer applies. Feel free to post a new issue if there are problems with the current modkit.)
