### ISSUE TITLE
oops the game crashed

### ISSUE THREAD

**Issue by jcresdee** [keeptalkinggame/ktanemodkit#23]
Help needed,

I have installed many versions of unity including the version mentioned in the readme.md file and the version named in the modkit project settings.

Below is a list of the Unity versions I have tried:

Unity 5.4.3f1 (64-bit)
Unity 5.4.3p3 (64-bit)
Unity 5.6.4f1 (64-bit)
Unity 2017.1.0f3 (64-bit)
Unity 2017.1.0p4 (64-bit)
Unity 2017.2.0f3 (64-bit)

Selecting Build AssetBundle throws no errors but when I copy the build contents to the mods folder and start the game I am asked if I want to enable mods. Selecting yes then crashes the game after a short delay. 

I have attached the contents of the error folder; although the crash dump file is not a supported type.

[error.log](https://github.com/keeptalkinggame/ktanemodkit/files/1495341/error.log)
[output_log.txt](https://github.com/keeptalkinggame/ktanemodkit/files/1495342/output_log.txt)

Any help would be appreciated.

Jarvis

**Comment by ashbash1987** [comment]
Are you trying to use the current master against the current main release on Steam, or the active public beta?

EDIT: Just updating with more info.

As it stands, there are two versions of KTaNE available to use for the public, the current release version and the public beta version.

## Current 'Release'
The current release is built upon Unity 5.4.x, and as such any mods should also be built within this Unity environment. If you need a version of ktanemodkit that works with this Unity, [use this particular version of the repo](https://github.com/keeptalkinggame/ktanemodkit/tree/b1260a0fb98d4c7687b608623ee1d8cc840d8692). If you use the latest ktanemodkit instead, you'll get badness happening.

## Current 'Beta'
The current beta is built upon Unity 2017.1.x, and again, any such mods that are rebuilt should also be built within this Unity environment, however older mods should still be able to load sufficiently in the basic case; some 5.4.x mods that use more complex Unity features and/or custom shaders may not work properly in the current 'beta' of the game until rebuilt and updated.

Judging from the output_log.txt, you're loading into the current 'release' version of KTaNE (as it says it loaded engine version 5.4.3p3) but it mentions object types in the examples that only appear as of the recent ktanemodkit that only supports 2017.1.x (e.g. BombCreator). From this I see there are two options for you:

1. Use the older ktanemodkit as mentioned above if you want to continue using the current public release and build with Unity 5.4.x.
2. Change to the public beta of KTaNE on Steam and continue to build with the latest ktanemodkit under 2017.1.x.

**Comment by jcresdee** [comment]
I'm using the current main release on steam with the master from github.

Thanks.

**Comment by ashbash1987** [comment]
You should check the edit I made to my original post, as it'll cover what you need to do to fix up your problem :)

**Comment by LtTops** [comment]
Had the same issue and switching to the active public beta fixed the issue for me.  Thanks.

**Comment by jcresdee** [comment]
Great, that has helped. thanks.
