### ISSUE TITLE
I'm getting "Compilation failed!"

### ISSUE THREAD

**Issue by bcetin** [keeptalkinggame/ktanemodkit#3]
Gettting this error after trying to build assetbundle. Did not changed anything in project file.

![ss](https://cloud.githubusercontent.com/assets/15525508/17614927/0d38b33c-6073-11e6-9cae-010aea88cdf8.png)

Here is the full text:
Failed to build AssetBundle: Compilation failed!
  at AssetBundler.CompileAssemblyWithEditor () [0x00279] in C:\Users\burak\Desktop\Ktane Module!\ktanemodkit-master\ktanemodkit-master\Assets\Editor\Scripts\AssetBundler.cs:285 
  at AssetBundler.BuildModBundle (Boolean useMSBuild) [0x000b8] in C:\Users\burak\Desktop\Ktane Module!\ktanemodkit-master\ktanemodkit-master\Assets\Editor\Scripts\AssetBundler.cs:117 
UnityEngine.Debug:LogErrorFormat(String, Object[])
AssetBundler:BuildModBundle(Boolean) (at Assets/Editor/Scripts/AssetBundler.cs:139)
AssetBundler:BuildAllAssetBundles_WithEditorUtility() (at Assets/Editor/Scripts/AssetBundler.cs:70)

I have 2 theories:

1) I don't have Visual Studio downloaded. If that could be a problem. (Using MonoDevelop for my own stuff)
2) Can unity version gap cause problems?

Note: I am PRETTY NEW to github so I hope this is the right place to write this. Have a nice day!

**Comment by ashbash1987** [comment]
_(This is from someone using Visual Studio, so may not be helpful to you...)_
Normally, if this happens I would trigger a compile in Visual Studio directly and then also go into play mode in Unity briefly, then try it again.

If all else fails, check your 'Library/UnityAssemblies' folder in your project directory and see if there's 'UnityEngine' in there somewhere. If not, try copying it in from the Unity program files (I fail to remember where the assemblies are specifically, hopefully a Google search will yield answers). After copying that in, try doing an asset bundle again and see what happens.

Hopefully Brian or Ben will be able to help you out further - just thought I'd chuck in my two pence as I have had this happen to me sporadically in the past.

**Comment by bfdev** [comment]
I've made a change to the AssetBundler as sometimes Unity doesn't populate the UnityAssemblies folder in the library, it will now grab the UnityEngine.dll right from the Unity Editor Managed dll folder so this should be safe for all computers. I believe this should fix your problem when you grab the newest version of the modkit.

**Comment by bcetin** [comment]
Redownlading seems to solved the problem. Thanks! (I don't know how to close the issue. B/ Can you please do that?)
